### ISSUE TITLE
Build of the Plugin fails on linux or mac

### ISSUE THREAD

**Issue by bulldog98** [hartmannaf/PokemonCheatPlugin#12]
The build fails on linux, because the build.py code uses os specific code.

**Comment by bulldog98** [comment]
Can be fixed by using [build.py patch](https://github.com/mid-kid/ntr_helloworld/blob/35a2af9e404c954545e763e071b86a39230b6af7/build.py) of @mid-kid

**Comment by hartmannaf** [comment]
I will look into it, especialy since im starting to move my development and compiling over to a linux server.
