### ISSUE TITLE
PLG

### ISSUE THREAD

**Issue by zhsxhd** [hartmannaf/PokemonCheatPlugin#15]
Help,i'm a beginner.I read the "readme" carefully,but i don't know how to use the plugin anyway.So,how can i get the "cheat.plg"? It's my easy way .Thank you!

**Comment by Hartie95** [comment]
You need to setup NTR CFW first, and after that you need to get the zip from here: https://github.com/hartmannaf/PokemonCheatPlugin/releases

then you need to create a plugin Folder on your sd-card and copy the contend of the zip to your sd-card. After that  you should have chet.plg files in teh folder for the games (for Pokemon X:  /plugin/0004000000055D00/cheat.plg)
