### ISSUE TITLE
5x Shiny Pokemon in horde (instead of just 1)

### ISSUE THREAD

**Issue by Favna** [hartmannaf/PokemonCheatPlugin#9]
We all know those photoshopped images of people reportedly getting 5 shinies in 1 single horde but wouldn't it be epic to **_actually_** get 5 shinies in 1 horde? I can already see myself making a fake "tableflip" style reaction video with NTR Viewer _Kappa_

**Comment by MrNbaYoh** [comment]
It is possible with the all shiny cheat

**Comment by Favna** [comment]
Hm well it only works when using the "*Pokemon Generation modifier(thanks to MrNbaYoh) *All Shiny Pokemon" cheat, but I would like it to work even when encountering the REAL pokemon from that route. Not random Pokemon. And the All Shiny code only makes ONE shiny.

In Alpha Sapphire anyway

**Comment by MrNbaYoh** [comment]
The zone you said it works does not randomize.

**Comment by Favna** [comment]
Oops yes my bad! That was the wild modifier messing up!
